# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79d76b78dd2ebed6a7874905e464a5e2dc6568874a037aaed7f730fcdb4f44d10624d95fe2c237b60ec36e196e48100b85f23ce22ecc29abf0427da9c56eecc2

test:
  secret_key_base: c5c0eea724c8be76538c3b20ccd88f8e8df2bcec5414a71713fd84ed1814f170e508ab3e962a830f3d60b2869b56d55d4c9ca89ba3d930c0f537ce1e62129bca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
